name: Label PR on Create

on:
  pull_request:
    types:
      - opened

jobs:
  label_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add Label to PR
        uses: ./add-label-action
        with:
          pr_number: ${{ github.event.pull_request.number }}
          label: 'new pull request'